#!/bin/sh

mkdir -p ${HOME}/.local/scripts

cp update ${HOME}/.local/scripts
chmod +x ${HOME}/.local/scripts/update
cp update.config ${HOME}/.local/scripts

cp update_world ${HOME}/.local/scripts
chmod +x ${HOME}/.local/scripts/update_world
cp update_world.config ${HOME}/.local/scripts

cp update_wrapper ${HOME}/.local/scripts

today=$(date '+%s')

# Configure the two log files 
echo ${today} > /tmp/update_ports.log
echo ${today} > /tmp/update_world.log

echo "(sleep 60 && ${HOME}/.local/scripts/update_wrapper) &" >> ${HOME}/.config/openbox/autostart.sh
