#!/bin/sh

__read_property(){
	local input="$@"
	temp=`cat ${config_file} | sed 's/\"//g' | grep -w ${input} | cut -d ":" -f2`
	echo ${temp##*|}
}

default_dir=${HOME}/.local/scripts
config_file=${default_dir}/update.config
timestamp=$(date +%s)
update_ports_frequency_in_days=$(__read_property update_ports_frequency_in_days)
update_world_frequency_in_days=$(__read_property update_world_frequency_in_days)

mkdir -p ${default_dir}

cp update ${default_dir}
chmod +x ${default_dir}/update_ports
cp update.config ${default_dir}

cp update_world ${default_dir}
chmod +x ${default_dir}/update_world
cp update_world.config ${default_dir}

cp update_pkg ${default_dir}
chmod +x ${default_dir}/update_pkg

cp update_wrapper ${default_dir}

cat >> /tmp/crontab_${timestamp}.tmp <<'EOF'
SHELL=/bin/sh
PATH=/etc:/bin:/sbin:/usr/bin:/usr/sbin
DISPLAY=:0.0
# Order of crontab fields
# minute	hour	mday	month	wday	command
* * */${update_ports_frequency_in_days} * * ${HOME}/.local/scripts/update_wrapper -p >/dev/null 2>&1
* * */${update_world_frequency_in_days} * * ${HOME}/.local/scripts/update_wrapper -w >/dev/null 2>&1
EOF

crontab -l
if [ $? -eq 1 ]
then
    # No crontab existing. Create an empty file
    cat >> /tmp/empty_crontab_${timestamp}.tmp <<'EOF'
SHELL=/bin/sh
PATH=/etc:/bin:/sbin:/usr/bin:/usr/sbin
DISPLAY=:0.0
# Order of crontab fields
# minute	hour	mday	month	wday	command
EOF
    cat empty_crontab_${timestamp}.tmp | crontab -
    rm empty_crontab_${timestamp}.tmp
fi

# Copy the current crontab into a temporary file
crontab -l > /tmp/current_crontab.tmp

# Merge the changes into a final file
sdiff -o /tmp/current_crontab.final /tmp/current_crontab.tmp /tmp/crontab_${timestamp}.tmp

# We do not need to append anything as the crontab has already been merged
# (crontab -l; cat /tmp/current_crontab.final | crontab -

# Put the merged entries into the crontab file
cat /tmp/current_crontab.final | crontab -

# Check the crontab file before ending the script
crontab -e

rm /tmp/crontab_${timestamp}.tmp
rm /tmp/current_crontab.tmp
rm /tmp/current_crontab.final

exit 0