#!/bin/sh

# Start functions
# Print out the help
__usage(){
    echo "usage: update_world [-c | [-ue | [-s step_id [-su | [-h]]]]]"
}

__confirm(){
	printf 'press [ENTER] to continue'
	read dummy
}

__read_property(){
	input="$@"
	temp=`cat ${config_file} | sed 's/\"//g' | grep -w ${input} | cut -d ":" -f2`
	echo ${temp##*|}
}

timestamp=$(date +%s)
step=1
executed_step=1
config_file=${HOME}/.local/scripts/update_script/update_world.config
log_file=/tmp/update_world.log
today=$(date '+%s')

f_update="true"
f_update_existing="false"
f_singleuser="false"
f_step="false"

while [ "$1" != "" ]; do
    case $1 in
    	-c | --config-file)		shift
                                config_file=$1
                                ;;
        -o | --output )			shift
								log_file=$1
								;;
		-ue | --update-existing) shift
                                f_update_existing="true"
                                f_update="false"
                                f_singleuser="false"
                                ;;
		-s | --step)		    shift
                                step=$1
                                f_step="true"
                                ;;
		-su | --single-user )	shift
                                f_singleuser="true"
                                f_update="false"
                                ;;
        -h | --help )           __usage
                                exit
                                ;;
        * )                     __usage
                                exit 1
    esac
    shift
done

# properties="server version branch log folders_to_backup kernel src dest arch"
server=$(__read_property server)
version=$(__read_property version)
branch=$(__read_property branch)
log=$(__read_property log)
folders_to_backup=$(__read_property folders_to_backup)
src=$(__read_property src)
kernel=$(__read_property kernel)
dest=$(__read_property dest)
arch=$(__read_property arch)
wlan_if=$(__read_property wlan_if)
keyboard_layout=$(__read_property keyboard_layout)

if [ "${f_update}" == "true" ]
then		
	if [ $step -le $executed_step ] || [ "${f_step}" == "false" ] 
	then
		# Check if the kernel exists
		if [ -f "$src/sys/$arch/conf/$kernel" ] 
		then
			echo "Backing-up Kernel to" $dest
			__confirm
			cp $src/sys/$arch/conf/$kernel $dest/
		else
			echo "File $src/sys/$arch/conf/$kernel does not exist."
		fi
		
		# Check if src exists
		if [ -d /usr/src ] 
		then 
			echo "Backing-up /usr/src to" $dest/src$timestamp
			__confirm
			mv $src $dest/src$timestamp
		else
			echo "File $src/sys/$arch/conf/$kernel does not exist."
		fi
		
		echo "Step 1) Back-up of additional folder(s) is starting..."
		for folder_with_full_path in $folders_to_backup
		do
			if [ -d "$folder_with_full_path" ] 
			then 
				# It gets the folder name from the full path
				folder=$(basename $folder_with_full_path)
				echo "Backing-up" $folder_with_full_path"/ to" $dest"/"$folder$timestamp 
				__confirm
				mkdir -p $dest/$folder$timestamp
				cp -rv $folder_with_full_path/ $dest/$folder$timestamp
			else
				echo $folder_with_full_path does not exist
			fi	
		done		
	else
		echo "Skipped Step 1)"
	fi
	
	executed_step=$((executed_step+1))
	
	if [ $step -le $executed_step ] || [ "${f_step}" == "false" ] 
	then
		# First checkout
		if [ "${f_update_existing}" == "false" ]
		then				
			echo "Step 2) Checkout Freebsd sources" $branch "version " $version
			__confirm
			svn checkout https://$server/base/$branch/$version/ $src
		fi
		# For all the other updates
		if [ "${f_update_existing}" == "true" ]
		then		
			echo "Step 2) Updating Freebsd sources" $branch "version " $version
			__confirm
			svn update $src
		fi
		__confirm
	else
		echo "Skipped Step 2)"
	fi
	
	executed_step=$((executed_step+1))

	if [ $step -le $executed_step ] || [ "${f_step}" == "false" ] 
	then
		# Various cleaning 
		echo "Step 3) Perform various cleaning before building world" 
		chflags -R noschg /usr/obj/*
		rm -rf /usr/obj
		__confirm
	else
		echo "Skipped Step 3)"
	fi

	executed_step=$((executed_step+1))	
	cd $src
		
	# Output redirection is missing
	if [ $step -le $executed_step ] || [ "${f_step}" == "false" ] 
	then
		echo "Step 4) Building World"
		make buildworld
		__confirm
	else
		echo "Skipped Step 4)"
	fi

	executed_step=$((executed_step+1))
	
	if [ $step -le $executed_step ] || [ "${f_step}" == "false" ] 
	then
		echo "Step 5) Building Kernel"
		make buildkernel KERNCONF=$kernel
		__confirm
	else
		echo "Skipped Step 5)"
	fi

	executed_step=$((executed_step+1))
		
	if [ $step -le $executed_step ] || [ "${f_step}" == "false" ] 
	then	
		echo "Step 6) Installing Kernel"
		make installkernel KERNCONF=$kernel
		__confirm
	else
		echo "Skipped Step 6)"
	fi

	echo ${today} > ${log_file}

	echo "Step 7) Reboot the system in single user mode..."
	echo "Once in single user mode, execute the following command 'mount -u / && mount -a -t ufs' and then run '%install_dir%/update_world -su'" 
	__confirm
	shutwdown -h now
fi

if [ "${f_singleuser}" == "true" ]
then
	# After reboot in single-user mode
	# echo "Mount root and Mounting UFS File System"
	# mount -u / && mount -a -t ufs
	# confirm

	echo "Mounting Swap Partition"
	swapon -a
	__confirm

	echo "Keyboar Layout changed to" $keyboard_layout
	setxkbmap $keyboard_layout
	__confirm

	echo "Fixing Timezone"
	adjkerntz -i
	__confirm

	echo "Start merging"
	mergemaster -p
	__confirm

	echo "Installing World"
	cd $src
	make installworld

	echo "Merging and deleting old libraries"
	mergemaster -iF
	make delete-old
	make delete-old-libs

	read -p "Do you want to recompile all ports? (y/n): " answer
    case $answer in
        [Yy]* ) /etc/rc.d/netif;
				__confirm;
				dhclient $wlan_if
				__confirm;
				portupgrade -fa
				break;;
        [Nn]* ) exit;;
    esac

    # TODO: this will most likely not work in single user mode a the path is not mounted
    echo ${today} > ${log_file}
fi

exit 0