#!/bin/sh

read_property(){
	input="$@"
	temp=`cat $config_file | sed 's/\"//g' | grep -w $input | cut -d ":" -f2`
	echo ${temp##*|}
}

confirm(){
	printf 'press [ENTER] to continue'
	read dummy
}

end(){
	printf 'The user has no right to update'
	printf '\n'
	printf 'press [ENTER] to finish'
	read dummy 
}

is_user_allowed_to_update(){
	group=$(id -G -n $(whoami) | grep -o "wheel")
	if [ "${group}" == "wheel" ]; then
		echo true
	else
		echo false
	fi
}

update_ports_log=/tmp/update_script.log
update_world_log=/tmp/update_world.log
default_dir=${HOME}/.local/scripts
config_file=${default_dir}/update.config
config_world_file=${default_dir}/update_world.config
batch_update=''

last_exec_update_ports=$(head -n 1 ${update_ports_log})
last_exec_update_world=$(head -n 1 ${update_world_log})
today=$(date '+%s')

update_ports_frequency=$(read_property update_frequency_in_days)
update_world_frequency=$(read_property update_world_frequency_in_days)
is_user_allowed=$(is_user_allowed_to_update)
batch_update_flag=$(read_property batch)
update_with=$(read_property update_with)

if [ "${is_user_allowed}" == "false" ]; then
	end
	exit
fi

if [ "${batch_update_flag}" == "true" ]; then
	batch_update='-b'
fi

days=$(( (today - last_exec_update_ports) / 86400 ))
echo "Last update ports executed" ${days} "days ago"

if [ $days -gt $update_ports_frequency ]; then
	if [ "${update_with}" == "pkg" ]; then
		xterm -title "Update Ports with PKG" -e su root -c "${HOME}/.local/scripts/update_pkg"
	elif [ "${update_with}" == "port" ]; then
		xterm -title "Update Ports with PORTUPGRADE" -e su root -c "${HOME}/.local/scripts/update ${batch_update}"
	else
		echo "[ERROR] Option not recognised"
		exit 1
	fi
fi

days=$(( (today - last_exec_update_world) / 86400 ))
echo "Last update world executed" ${days} "days ago"

if [ $days -gt $update_world_frequency ]; then
	confirm
	xterm -title "Update World" -e su root -c "${HOME}/.local/scripts/update_world -c ${config_world_file}"
fi

exit
